### ISSUE TITLE
Encoding

### ISSUE THREAD

**Issue by lxs602** [shawkynasr/HSK-official-Query-System#1]
Hi,

A suggestion. 

Many people have not heard of character encodings, and Excel does not offer automatic detection, even in the latest version, 365. 

Choosing the right encoding for csv files may confuse many users.

Perhaps the files could also be offered as odf or xlsx files?  

Utf-8 might be a better bet for the csv files themselves.

L

**Comment by shawkynasr** [comment]
Hi,
I see, office 2021 will support:
- CSV (UTF-8) support

I uploaded xlsx files in release:
[You can download it](https://github.com/shawkynasr/HSK-official-Query-System/releases/tag/2.0)

**Comment by shawkynasr** [comment]
Csv files, better to use editor to open it like: **EmEditor or notepad++**

"Utf-8 might be a better bet for the csv"
**Yes, encoding for csv is utf-8**

**Comment by lxs602** [comment]
Hi,

词汇.csv: utf-8 with confidence 0.99
<a href=https://github.com/shawkynasr/HSK-official-Query-System/blob/main/%E6%B1%89%E5%AD%97.csv>汉字.csv</a>: GB2312 with confidence 0.99  <---- Check this one
语法.csv: utf-8 with confidence 0.99
音节.csv: utf-8 with confidence 0.99

I can see the rest are all utf-8 :)

**Comment by lxs602** [comment]
> Hi,
> I see, office 2021 will support:
> 
> * CSV (UTF-8) support
> 
> I uploaded xlsx files in release:
> [You can download it](https://github.com/shawkynasr/HSK-official-Query-System/releases/tag/2.0)

Thanks, I had not looked at the release, only the csv files

**Comment by shawkynasr** [comment]
Many thanks!

fixed
