### ISSUE TITLE
Column no. 525 is missing

### ISSUE THREAD

**Issue by rodrigo-morales-1** [shawkynasr/HSK-official-Query-System#3]
File [词汇.csv](https://github.com/shawkynasr/HSK-official-Query-System/blob/main/%E8%AF%8D%E6%B1%87.csv) is missing column no. 525. When you scroll through the column that contain the numbers, you can see that it goes from 524 to 526. [This is the direct link to that part](https://github.com/shawkynasr/HSK-official-Query-System/blob/main/词汇.csv#L525).

This makes the CSV to show 11093 numbered rows, when actually the official list only shows 11092 rows.

**Comment by shawkynasr** [comment]
Thanks @rdrg109 fixed.

You can download csv files and excel files.
[2.1](https://github.com/shawkynasr/HSK-official-Query-System/releases/tag/2.1)
