### ISSUE TITLE
The number of Characters didn't match the specification

### ISSUE THREAD

**Issue by ofou** [shawkynasr/HSK-official-Query-System#5]
Based information [published](http://www.moe.gov.cn/jyb_xwfb/gzdt_gzdt/s5987/202103/W020210329527301787356.pdf) by the International Chinese Education (世界汉语教学), the number of characters didn't match. 

https://github.com/shawkynasr/HSK-official-Query-System/blob/b8b8abcfc649310cb90ceca26b7203e15d97fcaf/%E6%B1%89%E5%AD%97.csv#L3150

Actual count from vocabulary file is 3149. It should be a total of 3000:

![](https://ltl-school.com/wp-content/sites/16/vjdaz416z3051.jpg)

**Comment by ofou** [comment]
This is what I'm receiving from the current system. So, **149** more characters, and **4** more grammatical items. In which should we allocate those changes? Are they updates?

|       | syllables | characters | words | grammar |
|-------|-----------|------------|-------|---------|
| Total | 1110      | **3149**       | 11092 | **576**     |

**Comment by shawkynasr** [comment]
Hi Omar,
    that photo part of paper research.
Anyway, There are book of list and official website [moe](http://www.moe.gov.cn/jyb_xwfb/gzdt_gzdt/s5987/202103/t20210329_523304.html)

**Comment by shawkynasr** [comment]
I will re-check it

Today, I will fix the grammar part, next days characters

**Comment by shawkynasr** [comment]
Grammar, only it was 121 part ※“是……的”表示强调 (见【二60】“‘是......的’ 句1”和【四42 】“‘是......的’句2") 

Grammar part only 572, not 576.

**Comment by shawkynasr** [comment]
Grammar fixed 

https://github.com/shawkynasr/HSK-official-Query-System/blob/main/%E8%AF%AD%E6%B3%95%202023.csv

You can check it now.

**Comment by shawkynasr** [comment]
About characters, I remembered why more than 3000. it was because of 同音词 Homophone same character has two or more.

Like: 
6,六级,挨,āi
7,六级,挨,ái

Yes, book don't have pinyin, that why only show 3000 characters.

**Comment by shawkynasr** [comment]
FYI, I used [Chinese Proficiency Grading Standards for International Chinese Language Education (National Standard: Application and Interpretation)](https://www.blcup.com/EnPInfo/index/10867#001) to re-check Grammar and characters.

That book most accurate one more than website of HSK.

**Comment by shawkynasr** [comment]
fixed all

**Comment by shawkynasr** [comment]
You can check it

[[汉字表 2023 （only 3000)](https://github.com/shawkynasr/HSK-official-Query-System/blob/main/%E6%B1%89%E5%AD%97%E8%A1%A8%202023%20%EF%BC%88only%203000).csv))](https://github.com/shawkynasr/HSK-official-Query-System/blob/main/%E6%B1%89%E5%AD%97%E8%A1%A8%202023%20%EF%BC%88only%203000).csv)

**Comment by shawkynasr** [comment]
You can download all of files

[version 3.0](https://github.com/shawkynasr/HSK-official-Query-System/releases/tag/3.0)

**Comment by ofou** [comment]
Awesome work, I think it will be useful to publish a list of homophones as well. I did an exploratory analysis and it's not a big list, but it's an important distinction, especially for both words and  characters.
